### ISSUE TITLE
Path problem during preprocessing

### ISSUE THREAD

**Issue by yct111** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#18]
I'm typing in at the terminal
(abc) E:\TCN_LIPREADING_ROOT\TCN_LIPREADING_ROOT\preprocessing>
python crop_mouI'm typing in at the terminalth_from_video.py --video-direc E:/TCN_LIPREADING_ROOT/TCN_LIPREADING_ROOT/landmarks/LRW_landmarks/ --land
mark-direc E:/TCN_LIPREADING_ROOT/TCN_LIPREADING_ROOT/landmarks/ --save-direc E:/TCN_LIPREADING_ROOT/TCN_LIPREADING_ROOT/datasets/visual_data/
idx: 0  Processing.     ABOUT/test/ABOUT_00001
Traceback (most recent call last):
  File "crop_mouth_from_video.py", line 139, in <module>
    assert os.path.isfile(video_pathname), "File does not exist. Path input: {}".format(video_pathname)
AssertionError: File does not exist. Path input: E:/TCN_LIPREADING_ROOT/TCN_LIPREADING_ROOT/landmarks/LRW_landmarks/ABOUT/test/ABOUT_00001.mp4
I don't know why

**Comment by mpc001** [comment]
#16

**Comment by yct111** [comment]
Sorry to bother you again.We call the original LRW directory that includes timestamps (.txt) as <ANNONATION-DIRECTORY>.Is this path the original LRW data set path?I can't find the time stamp.

**Comment by kategia** [comment]
Hi,
I'm having the  same issue I changed the path to windows and I still get an error:
RuntimeError: Error opening 'D:\\Lipreading_using_Temporal_Convolutional_Networks\\lipread_mp4\\ABOUT\\test\\ABOUT_00001.mp4': File contains data in an unknown format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Lipreading_using_Temporal_Convolutional_Networks/preprocessing/extract_audio_from_video.py", line 43, in <module>
    data = librosa.load(video_pathname, sr=16000)[0][-19456:]
  File "C:\Users\KATE\Anaconda3\lib\site-packages\librosa\core\audio.py", line 166, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "C:\Users\KATE\Anaconda3\lib\site-packages\librosa\core\audio.py", line 190, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "C:\Users\KATE\Anaconda3\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError

**Comment by yct111** [comment]
File "main.py", line 242, in main
    acc_avg_val, loss_avg_val = evaluate(model, dset_loaders['val'], criterion)
  File "main.py", line 115, in evaluate
    print('{} in total\tCR: {}'.format( len(dset_loader.dataset), running_corrects/len(dset_loader.dataset)))
ZeroDivisionError: float division by zero
How can we solve this problem?
