### ISSUE TITLE
Error in extract_audio_from_video

### ISSUE THREAD

**Issue by kategia** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#20]
Hi,
I'm having an issue when processing the audio and I get an error. I don't know whats wrong since the code sees the dataset but says its an unknown format. Any ideas?
Thank you 

RuntimeError: Error opening 'D:\Lipreading_using_Temporal_Convolutional_Networks\lipread_mp4\ABOUT\test\ABOUT_00001.mp4': File contains data in an unknown format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:/Lipreading_using_Temporal_Convolutional_Networks/preprocessing/extract_audio_from_video.py", line 43, in
data = librosa.load(video_pathname, sr=16000)[0][-19456:]
File "C:\Users\KATE\Anaconda3\lib\site-packages\librosa\core\audio.py", line 166, in load
y, sr_native = __audioread_load(path, offset, duration, dtype)
File "C:\Users\KATE\Anaconda3\lib\site-packages\librosa\core\audio.py", line 190, in _audioread_load
with audioread.audio_open(path) as input_file:
File "C:\Users\KATE\Anaconda3\lib\site-packages\audioread_init.py", line 116, in audio_open
raise NoBackendError()
audioread.exceptions.NoBackendError

**Comment by mpc001** [comment]
Hi, could you check if you've installed `ffmpeg`?

**Comment by kategia** [comment]
Thank you for your response although it was installed  for some reason pycharm couldn't see it. How do we train the model for audiovisual? There are steps for audio only and visual only but how do we combine them( apologies if this is a silly question)?
