### ISSUE TITLE
Training using CPU

### ISSUE THREAD

**Issue by hasanm29** [mpc001/Lipreading_using_Temporal_Convolutional_Networks#41]
Hi, thanks for the training code.
Can we train the code using cpu only? 
What changes we need to make in that case?

**Comment by hasanm29** [comment]
I get the error when run the following command: I'm **using the repo in VMware** which is why **unable to use GPU**
@mpc001 , looking forward to hearing from you.

**CUDA_VISIBLE_DEVICES='' python3 main.py --config-path /home/ubuntu/TCN_LIPREADING_ROOT/Lipreading_using_Temporal_Convolutional_Networks/configs/lrw_resnet18_mstcn.json --annonation-direc /home/ubuntu/TCN_LIPREADING_ROOT/Lipreading_using_Temporal_Convolutional_Networks/LRW_data --data-dir /home/ubuntu/TCN_LIPREADING_ROOT/Lipreading_using_Temporal_Convolutional_Networks/datasets/visual_data**
Model and log being saved in: ./train_logs/tcn/2022-04-14T18:30:41
Traceback (most recent call last):
  File "main.py", line 261, in <module>
    main()
  File "main.py", line 201, in main
    model = get_model_from_json()
  File "main.py", line 181, in get_model_from_json
    model = Lipreading( modality=args.modality,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
**RuntimeError: The NVIDIA driver on your system is too old** (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

**Comment by jingtian-feng** [comment]
i use cpu to test just through delete all the ".cuda()" function in the main , but i can not bear the very very slow speed
hope to help you
